GET http://artists.teefury.com/api/admin/submissions/DECLINED
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTM0NCwiY29udGFjdEVtYWlsIjoiYnRyYW5AdGVlZnVyeS5jb20iLCJpc19hZG1pbiI6MSwiaWF0IjoxNTkyMjQ3MTA3LCJleHAiOjE2MDAwMjMxMDd9.FHJT9hAkcl7lNIo70rdFtaIV83QBZWXrqjPw1gNI6ss

### 
DELETE http://artists.teefury.com/api/admin/submissions/declined-all-art-files
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTM0NCwiY29udGFjdEVtYWlsIjoiYnRyYW5AdGVlZnVyeS5jb20iLCJpc19hZG1pbiI6MSwiaWF0IjoxNTkyMjQ3MTA3LCJleHAiOjE2MDAwMjMxMDd9.FHJT9hAkcl7lNIo70rdFtaIV83QBZWXrqjPw1gNI6ss
